---
output: 
    github_document:
        toc: true
        toc_depth: 3
---

# SETr script development  

This page is the document hub and GitHub page for the development of scripts for the NERRS Science Collaborative-funded project *__'Is marsh surface tracking sea level change? Developing tools and visualizations for NERRS Sentinel Site Data'__*.

## Email list sign-up  

**[Click here](https://goo.gl/forms/CLWmBm2cexEhEhZt1)**  

# Coming Up: Technical Workshop in Virginia!  

__July 15-16, 2019__  

*Objectives:*  

1.  Present R scripts and workflows developed for this project  
2.  Present Reserve-level reports and maps  
3.  Present National synthesis  
4.  Discuss Environmental Statistics and SET datasets  

View and make suggestions on the [draft agenda](https://docs.google.com/document/d/1sS_sPXOSiFwyOeIeL4DK96Nnot4F3wMXMnpvqFCj70A/edit?usp=sharing)  

# Project Summary  

Can marsh vegetation communities keep pace with sea level rise? To address this critical coastal management issue, the NERRS established a Sentinel Site Application Module of the System-Wide Monitoring Program. A centerpiece is the use of Surface Elevation Tables (SETs) to precisely measure marsh surface elevation over time. Many reserves have been collecting these data for years, resulting in a need for both Reserve-specific and System-wide data processing and analyses. We will create standardized tools to quality-check SET data, perform trend analyses, and produce informative visualizations for varied audiences. A technical team, to include a statistician, will focus on creating quality-control (QC) and analysis tools, while an outreach team will craft visualizations for communication products and educational curricula. In-person and webinar workshops will be held to train end-users on both technical and outreach tools. Participating Reserves will receive site-specific trend analyses, visualizations, and a national synthesis of surface elevation change vs. sea level trends. This project will catalyze the use of Sentinel Site data by providing Reserves the tools they need to analyze, understand, and communicate these important, underutilized datasets.  


# Important Project Links  

+  __Sign up for our email lists__ through [this Google form](https://goo.gl/forms/CLWmBm2cexEhEhZt1)  
+  The first round of R code is at [the main GitHub repository](https://github.com/swmpkim/SETr_script_development)  
+  Code for each individual data set's transormation into this project's formats is [on Github: SETr_data_transformations](https://github.com/swmpkim/SETr_data_transformations)
+  R code for Reserve-level workflows is being developed [on this GitHub page](https://github.com/swmpkim/SETr_Reserve_Template)
+  Watch the [recording of the Kickoff Webinar](https://youtu.be/Gc7YedK1Ek0) from 9/25/2018  
+  See [slides from the Kickoff Webinar](https://drive.google.com/file/d/1LIT80g_CfRJH2dKXbORHGesQy1uNUJP7/view?usp=sharing)  
+  Learn more about the [NERRS Science Collaborative](http://graham.umich.edu/water/nerrs)

# Monthly Call Notes  

+  [2018-10-03 call notes](https://drive.google.com/file/d/1zY7R2lVdmK55RjfMdRA9T9demga-JQ9G/view?usp=sharing)  
+  [2018-11-14](https://docs.google.com/document/d/1VeeC3II5p5dBNeFu-5YOTQ4BTEOp6vOk3iMdIGL_czY/edit?usp=sharing) - agenda only  
+  [2018-12-05 call notes](https://docs.google.com/document/d/1aPa10OZSupNXOZ5Lqvnm3WFn-ml-m6pxmbO_635APHo/edit?usp=sharing)  
+  [2019-01-02 call notes](https://docs.google.com/document/d/1FBiCwsmRTZBzv2r5Jivejd9CDH5PMTl9Nl6L2YTNs3Y/edit?usp=sharing)  
+  [2019-02-06](https://docs.google.com/document/d/1N_vqzJ_Gw1tDz1KcsPX-vN1e72Q7lszEAxL7xKhjeBE/edit?usp=sharing) - agenda plus a few comments  
+  [2019-03-06 call notes](https://docs.google.com/document/d/1kUFrqOYmvoSWUPs05o_Y8acmtEnLFdziGJ6xbxlo-xA/edit?usp=sharing)  
+  [2019-04-03 call notes](https://docs.google.com/document/d/19XfNi2tOs-HACxHfqxb_4F5MEZCtKzyyrAAkGKII32Q/edit?usp=sharing)  
+  [2019-05-01 call notes](https://docs.google.com/document/d/1sXo0iAO8OdT7NpkUUL7gW0CkiF9B0lRWSfMjCzq-o9Y/edit?usp=sharing)  
+  Also check out and comment on our [suggested standard QA/QC codes for NERR SET data](https://docs.google.com/spreadsheets/d/1cqxi_Bz1CjpticfrPLf1_GgsoN2g_V1jlV9gAbzN6xw/edit?usp=sharing)  

# Useful References  

+  [Wickham 2014](https://www.jstatsoft.org/article/view/v059i10) - Tidy Data  
+  [Broman and Woo 2018](https://www.tandfonline.com/doi/abs/10.1080/00031305.2017.1375989) - Data Organization in Spreadsheets  
+  [Lynch et al. 2015](https://irma.nps.gov/DataStore/Reference/Profile/2225005) - NPS SET Monitoring Protocol 


Stay tuned for more!